### PR TITLE
Support @material-ui/core v1.0

### LINKED ISSUE #247: Not working with @material-ui/core v1.0.0
Hello,  
I think there is a problem with the recent `v1.0.0-rc.0`, which renames the namespace from `material-ui` to `@material-ui/core`.  
I didn't follow the discussion so I cannot really say why this was made, but it broke this library.  
Do you plan to update it to support `v1.0.0-rc.0`?  
Will you release a final version once v1.0.0 is final as well?  
  
Thanks!

### PR DESCRIPTION
**Pull request by andreapier**
I made some changes to support `@material-ui/core v1.0.0-rc.1`.  
I might have added some unnecessary changes, sorry if it is the case.  
The fact is, this is the first time I author changes for an npm module... not quite sure if this is the best way.  
There is definitely something to look into... I was not able to make the error message to work properly in `Select`. Material-ui removed the `helperText` prop, so the `mapError` function can't be easily adapted... I might be missing something in whch case I ask you to give me proper advice.  
Please review and merge as soon as possible so at least we can have it working even if not at 100%.  
Closes #247.

### CODE REVIEW

**Comment by mihirsoni** [comment]
@andreapier  could you resolve confilcts ?

**Review by mihirsoni — COMMENTED** [review]
Just neat : Could you use single quotes and newline at the end of file ?
This will make diff simpler and cleaner.

**Comment by andreapier** [comment]
Solved!  
Sorry for the inconvenience... Somehow I missed it :(

**Comment by andreapier** [comment]
@mihirsoni can you point me to which files do not have newline? I cannot find any.  
Thanks

**Comment by mihirsoni** [comment]
> @mihirsoni can you point me to which files do not have newline? I cannot find any.
Thanks

I'll saw one or two, but if that is okay. let's just go into single quotes and I'll review again ?
Also,  I guess your rebase hasn't been done properly. Could you verify that ?

**Comment by andreapier** [comment]
I am not that expert in git, so I might have screwed something.  
What do you mean by 'your rebase hasn't been done properly'?  
What do I need to do?

**Comment by mihirsoni** [comment]
Hi @andreapier  No issues.  I have tried to resolve them and created new pull request #251 on behalf of you. Could you please verify changes one time before I make an actual merge?

**Comment by mihirsoni** [comment]
Closing this in favor of #251

**Pull request closed without merging**
