### PR TITLE
fix autocomplete object list

### PR DESCRIPTION
**Pull request by bhml**
Not sure if this is the best way but it works fine. #24

### CODE REVIEW

**Comment by joshyboyrules** [comment]
any update on this?

**Comment by CalamarBicefalo** [comment]
We are waiting for this fix as well, is there a planned release for it?

**Comment by barnc** [comment]
I could really do with this too.

**Comment by lsunsi** [comment]
Yeah, this would be great. AutoComplete is hard to use in it's current state.

**Comment by stunaz** [comment]
indeed, allo @erikras

**Comment by MentalGear** [comment]
Could please someone look after this Pull request ?

**Comment by LeoLozes** [comment]
Any news on this?

**Comment by sleepycat** [comment]
@erikras Any plans to merge this PR?

**Comment by timglass** [comment]
+1 for this to be merged/fixed @erikras @Brian-Gaffney

**Comment by gDelgado14** [comment]
I see there are 2 failing checks. If resolving these checks is what's stopping the merge then please provide some guidance on how to resolve these checks (I've never worked with codecov and am overall new to tools such as codecov). Fixing this issue would be awesome though.

**Pull request merged**
