### PR TITLE
Support Material-UI v1

### PR DESCRIPTION
**Pull request by gfpacheco**
Addresses #165.

It's a really basic port, based mostly on copy and paste but it's working for me up until now.
I'm sorry I didn't deliver a better or more robust implementation, but I hope it saves you some time.

### CODE REVIEW

**Comment by mihirsoni** [comment]
@gfpacheco Could you resolve conflicts mentioned by github ?

**Comment by benaduggan** [comment]
@gfpacheco Do you know how long it will be before you're able to complete the merge conflicts?

**Comment by gfpacheco** [comment]
Sorry, I'm not finding time to do it and I don't think I'll be able to do it this week

**Comment by mihirsoni** [comment]
I have resolved conflicts and merged it for now. I'll start looking into others.

**Comment by tony-kerz** [comment]
@gfpacheco thanks so much for your effort in kicking this off!

(and thanks @mihirsoni for pitching in too!)

we love redux-form, we love material-ui, and we are bold enough to try to use material-ui 1.x in beta flux 😆

can anyone direct me to a reference sample of using the [select](https://material-ui-1dab0.firebaseapp.com/demos/selects/) control in this branch?

**Comment by tony-kerz** [comment]
@gfpacheco currently having an issue with radio control where it seems to render ok, but when i click a button, it doesn't show as selected (seems internal svg is supposed to change, but isn't). can you spot anything goofy in the code below?:
```
//...
import Radio from 'material-ui/Radio'
import {FormLabel, FormControl, FormControlLabel} from 'material-ui/Form'
import {TextField, RadioGroup} from '@gfpacheco/redux-form-material-ui'
import {reduxForm, Field} from 'redux-form'
//...
              <FormControl component="fieldset" required>
                <FormLabel component="legend">Gender</FormLabel>
                <Field name="gender" component={RadioGroup}>
                  <FormControlLabel value="male" control={<Radio />} label="Male" />
                  <FormControlLabel value="female" control={<Radio />} label="Female" />
                  <FormControlLabel value="other" control={<Radio />} label="Other" />
                </Field>
              </FormControl>
```

**Comment by mihirsoni** [comment]
@tony-kerz  Could you give some palyground that will be easy to reproduce. 
I am planning to release beta by end of this month most probably.

**Comment by tony-kerz** [comment]
hi @mihirsoni sure, here is [my playground at a suitable commit](https://github.com/tony-kerz/react-redux-scratch/commit/8c452e0ece39575dfc80ccf4e92505bee18a372d).

follow [the instructions](https://github.com/tony-kerz/react-redux-scratch/tree/8c452e0ece39575dfc80ccf4e92505bee18a372d#directions) to setup

also disable auth with a `config/local.js` file as [noted here](https://github.com/tony-kerz/react-redux-scratch/tree/8c452e0ece39575dfc80ccf4e92505bee18a372d#authorization)

then hit [this url](http://localhost:8080/#/people/person) and u should see the above `RadioGroup` issue in action.

hit me back with any issues, and appreciate your efforts on this 🙏

**Comment by tony-kerz** [comment]
fwiw as an example, i put together this implementation of `Select` accounting for the new mui 1.x components (`FormControl`, `InputLabel`, `FormHelperText`): 
```
import React from 'react'
import {FormControl, FormHelperText} from 'material-ui/Form'
import Input, {InputLabel} from 'material-ui/Input'
import {MenuItem} from 'material-ui/Menu'
import Select from 'material-ui/Select'

export default function({
  label,
  input: {name, value, onChange},
  meta: {touched, error, warning},
  options,
  className
}) {
  const _error = touched && (error || warning)
  const items = []
  for (const key in options) {
    items.push(<MenuItem value={key}>{options[key]}</MenuItem>)
  }
  return (
    <FormControl className={className} error={_error}>
      <InputLabel htmlFor={name}>{label || name}</InputLabel>
      <Select value={value} onChange={onChange} input={<Input id={name} />}>
        {items}
      </Select>
      {_error && <FormHelperText>{error || warning}</FormHelperText>}
    </FormControl>
  )
}
```
in this particular case, i am passing `options` as an object and constructing the `MenuItem`s on the fly, so can call like so:
```
        <Field
          className={classes.text}
          name="foo"
          label="Foo"
          component={Select}
          validate={[required()]}
          options={{'': '', a: 'a', b: 'b', c: 'c'}}
        />
```
but could also modify to use `children` with the expectation that it is called like:
```
        <Field
          className={classes.text}
          name="foo"
          label="Foo"
          component={Select}
          validate={[required()]}
        >
          <MenuItem value=""/>
          <MenuItem value="a">a</MenuItem>
          <MenuItem value="b">b</MenuItem>
          <MenuItem value="c">c</MenuItem>
        </Field>
```

**Pull request merged**
