### PR TITLE
allow @material-ui/core@^3.0.0 as a peer dep

### PR DESCRIPTION
**Pull request by jedwards1211**

### CODE REVIEW

**Comment by cvanem** [comment]
@mihirsoni 

Is it possible to get this PR merged with the 5.0 branch?  This fix should fix this build warning:

warning " > redux-form-material-ui@5.0.0-beta.3" has incorrect peer dependency "@material-ui/core@1".

**Comment by c4cv9** [comment]
yes plase

**Comment by mihirsoni** [comment]
I will release new version , and will try to make 5.0 as master branch. 

Apologize for the delay as I was involve in constant travel and relocating my self.

**Comment by anudeepjusanu** [comment]
Hi Is this merge done?

**Pull request merged**
